### ISSUE TITLE
python week4 ModuleNotFoundError: No module named 'controller'

### ISSUE THREAD

**Issue by josemotta** [DataStax-Academy/cassandra-workshop-series#17]
When I try to run week4-python I got an error, as the 'controller' package could not be located. What am I doing wrong?

Steps:
- goto Gitpod
- pip install Flask flask-cors cassandra-driver
- FLASK_ENV=development FLASK_APP=getting_started_with_astra.py flask run

Result:
gitpod /workspace/getting-started-with-astra-python $ FLASK_ENV=development FLASK_APP=getting_started_with_astra.py flask run
 * Serving Flask app "getting_started_with_astra.py" (lazy loading)
 * Environment: development
 * Debug mode: on
 * Running on http://127.0.0.1:5000/ (Press CTRL+C to quit)
 * Restarting with stat
 * Debugger is active!
 * Debugger PIN: 149-766-813
127.0.0.1 - - [25/Jul/2020 14:16:18] "GET / HTTP/1.1" 500 -
Traceback (most recent call last):
  File "/workspace/getting-started-with-astra-python/getting_started_with_astra.py", line 3, in <module>
    from controller.credentials_controller import credentials_controller
ModuleNotFoundError: No module named 'controller'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/workspace/.pip-modules/lib/python3.8/site-packages/flask/cli.py", line 338, in __call__
    self._flush_bg_loading_exception()
  File "/workspace/.pip-modules/lib/python3.8/site-packages/flask/cli.py", line 326, in _flush_bg_loading_exception
    reraise(*exc_info)
  File "/workspace/.pip-modules/lib/python3.8/site-packages/flask/_compat.py", line 39, in reraise
    raise value
  File "/workspace/.pip-modules/lib/python3.8/site-packages/flask/cli.py", line 314, in _load_app
    self._load_unlocked()
  File "/workspace/.pip-modules/lib/python3.8/site-packages/flask/cli.py", line 330, in _load_unlocked
    self._app = rv = self.loader()
  File "/workspace/.pip-modules/lib/python3.8/site-packages/flask/cli.py", line 388, in load_app
    app = locate_app(self, import_name, name)
  File "/workspace/.pip-modules/lib/python3.8/site-packages/flask/cli.py", line 245, in locate_app
    raise NoAppException(
flask.cli.NoAppException: While importing "getting-started-with-astra-python.getting_started_with_astra", an ImportError was raised:

Traceback (most recent call last):
  File "/workspace/.pip-modules/lib/python3.8/site-packages/flask/cli.py", line 240, in locate_app
    __import__(module_name)
  File "/workspace/getting-started-with-astra-python/getting_started_with_astra.py", line 3, in <module>
    from controller.credentials_controller import credentials_controller
ModuleNotFoundError: No module named 'controller'

**Comment by josemotta** [comment]
I figured out to fix this issue by filling the __init__.py properly inside modules folders. Not sure if all IDEs have the same behavior.

**Comment by clun** [comment]
Hello,

As of now this is the first time we heard about his issue.

- How did you edit the related ` init.py` ? Which modules folder ?

- Also why ? `FLASK_ENV=development FLASK_APP=getting_started_with_astra.py flask run`. Current procedure is but I am not an Python expert.

```
cd cassandra-workshop-series/week4-AppDev-api/getting-started-with-astra-python
python getting_started_with_astra.py
```

**Comment by bettinaswynnerton** [comment]
@josemotta, thanks for the feedback.  could you show how you filled the init.py, so we can make the changes?

**Comment by josemotta** [comment]
Hi, thanks @clun and @bettinaswynnerton for your support. Please check the link below the version I created as an exercise.

https://github.com/bampli/astra

https://github.com/bampli/astra/blob/master/controller/__init__.py
https://github.com/bampli/astra/blob/master/dao/__init__.py
https://github.com/bampli/astra/blob/master/model/__init__.py
https://github.com/bampli/astra/blob/master/service/__init__.py

**Comment by HadesArchitect** [comment]
Is it solved by now or is it still the issue?

**Comment by josemotta** [comment]
Hi, thanks for asking! It looks like some issue with VS Code that was fixed with proper .ini files.

I am now struggling to connect to Cassandra cluster, since I figured out that the current code has issues with Kind. Please note that it works fine with Astra cloud authentication (USE_ASTRA=true).

Exception has occurred: UnresolvableContactPoints {} File "e:_git\t1-astra\server\dao\session_manager.py", line 77, in connect cluster = Cluster(contact_points=connectionPoint, execution_profiles={'core': ep_graphson3}) File "e:_git\t1-astra\server\service\astra_service.py", line 32, in connect return self._session_manager.connect() File "e:_git\t1-astra\server\app.py", line 37, in hello astra_service.connect()

I am not able to find Cassandra server IP. To get more details please check this link:
https://github.com/bampli/t1-astra/blob/master/server/dao/session_manager.py

Also server/app.py was adjusted for USE_ASTRA=false:
https://github.com/bampli/t1-astra/blob/master/server/app.py
